### ISSUE TITLE
Always trying to read from non-existent Spring Cloud Config Server

### ISSUE THREAD

**Issue by dmfrey** [ordina-jworks/microservices-dashboard#102]
Because the Spring Cloud Config Client jar is on the classpath, the application is continually polling for localhost:8888 to read config data.  Is this required for the functionality of the application?

**Comment by andreasevers** [comment]
Did you add the jar yourself? Both the [sample applications](https://github.com/ordina-jworks/microservices-dashboard-server/tree/master/samples) immediately back off when localhost:8888 is not responding.

Could you try to set the following property?
`spring.cloud.config.failFast=true`

**Comment by jonatan-ivanov** [comment]
@dmfrey Create a file named `bootstrap.properties` into your resources directory and put this into it: `spring.cloud.config.enabled=false`.

@andreasevers Are you planning to disable cloud config? Or are you using it optionally for something? If so are you planning to conditionally switch it off?

**Comment by andreasevers** [comment]
@jonatan-ivanov We should indeed make it conditional. Everywhere we rolled out the dashboard we use spring-cloud-config, but it shouldn't be turned on by default.

PRs for this are welcome, otherwise we'll make the change as soon as we find the time.

**Comment by TYsewyn** [comment]
This will not be an issue anymore in 2.0.
Unfortunately the 1.x release had a lot of flaws and wasn't maintained.
Therefor I'm going to close this issue.

If you still have any questions, don't hesitate to reach out on Gitter or reopen this issue.
