### ISSUE TITLE
Provide link to the API documentation on clicking the resources

### ISSUE THREAD

**Issue by andreasevers** [ordina-jworks/microservices-dashboard#12]

**Comment by yannickvergeylenord** [comment]
Where can i find the links to the api documentation, they are not yet included in the json I receive

**Comment by andreasevers** [comment]
The url for documentation should be partially configurable.
A prefix and a suffix should be configurable, and the eventual configuration link should be composed as such:
"${prefix}${microservice-name}${suffix}".

**Comment by andreasevers** [comment]
Resources now have a "docs" entry in the details section of the json node.
These details (and the ones from any other node type) should be shown in the dialogbox when clicking on the node.
As for the docs, the link should be shown as part of the details in the dialog box as a link opening in a new window.
