### ISSUE TITLE
Filtering should cascade to other columns

### ISSUE THREAD

**Issue by andreasevers** [ordina-jworks/microservices-dashboard#15]
When filtering one column, the nodes that remain should impact the other columns as well.
For instance, if the backend column is filtered on CSL, the microservices column should only show those nodes that connect to any of the CSL backends.

This is how it is currently, and the idea is that only billing-transactions and billing-accounts remain in the microservices column.
<img width="677" alt="screen shot 2016-03-26 at 12 20 27" src="https://cloud.githubusercontent.com/assets/6663110/14059758/8357d9e6-f34d-11e5-9c7d-0551de093ea8.png">

Also important with this:
1. Filtering on 1 column should cascade filtering to other columns. Filtering on another column while the first column is filtered should be the common shared division of both filters. This feature can be lower priority if it is hard to implement.
2. A button to reset all filters should be added.

**Comment by yannickvergeylenord** [comment]
This is the case now:
Considering:

- resource can be source for a microservice (resource -> µservice)
- microservice can be source for another microservice (µservice <-> µservice)
- microservice can be source for a backend (µservice -> backend)
