### ISSUE TITLE
Status for virtual nodes should be VIRTUAL

### ISSUE THREAD

**Issue by andreasevers** [ordina-jworks/microservices-dashboard#19]
This can indicate virtual nodes, and when creating one with the + bubble at the bottom, the VIRTUAL status should be prefilled and unchangeable.

**Comment by andreasevers** [comment]
Status is successfully disabled once the node is created, but at the time the node is being created, I can still choose for DOWN or other statuses.
Please disable the box as well when clicking the plus bubble.

<img width="1024" alt="screen shot 2016-03-30 at 16 01 22" src="https://cloud.githubusercontent.com/assets/6663110/14144641/ce0035ec-f690-11e5-9af6-1dcf291f7602.png">

**Comment by yannickvergeylenord** [comment]
So actually the field status is a never editable field?
