### ISSUE TITLE
After filtering no links are shown

### ISSUE THREAD

**Issue by andreasevers** [ordina-jworks/microservices-dashboard#4]

**Comment by andreasevers** [comment]
Filtering the backends also removes all nodes from the other columns, including the links.

**Comment by yannickvergeylenord** [comment]
That is actually expected behavior, the only solution for this would be to have filters on each lane Or a way to indicate on which lane one wants to filter. I'll try figure something out asap.

**Comment by andreasevers** [comment]
Yes we need the ability to filter separately on each column.

On 23 March 2016 at 15:19, yannick vergeylen <notifications@github.com>
wrote:

> That is actually expected behavior, the only solution for this would be to
> have filters on each lane Or a way to indicate on which lane one wants to
> filter. I'll try figure something out asap.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ordina-jworks/microservices-dashboard/issues/4#issuecomment-200364066>
>



-- 
Andreas Evers
Krosan@gmail.com

- My blog: http://krosan.wordpress.com -

**Comment by andreasevers** [comment]
This should be top priority.
