### ISSUE TITLE
Wrong object notation

### ISSUE THREAD

**Issue by ryandegruyter** [ordina-jworks/microservices-dashboard#40]
graph.service.js

![image](https://cloud.githubusercontent.com/assets/12190633/16856637/9ff92512-4a1b-11e6-9fe4-f3c2b6b24fe7.png)

node.service.js too + maybe others

![image](https://cloud.githubusercontent.com/assets/12190633/16856707/f1f57a78-4a1b-11e6-87b9-e7c907a1986d.png)

gulp-angular-filesort together with gulp-inject are responsible for adding the app .js files to the index.html, which is not happening atm. Results in the uncaught Error: [$injector:modulerr].

**Comment by Turbots** [comment]
Before this, it was something like:
``` javascript
    var moo = {
        getGraph, getStates, getTypes, getGroups
    }
    return moo;
```

**Comment by ryandegruyter** [comment]
should be 
```
return {
  getGraph: getGraph,
  getStates: getStates,
  getTypes: getTypes,
  getGroups: getGroups,
};
```

or like before
```
var moo = {
  getGraph: getGraph,
  getStates: getStates,
  getTypes: getTypes,
  getGroups: getGroups,
};
return moo;
```

**Comment by ryandegruyter** [comment]
Ah! 
this
```
var moo = {
        getGraph, getStates, getTypes, getGroups
 }
return moo;
```
Is an es6 feature called "Object short notation", we need to use babel or typescript if we want to use 
the latest language features. Might be a good idea to setup.
