### ISSUE TITLE
Groups should be fetched dynamically instead of a fixed list

### ISSUE THREAD

**Issue by andreasevers** [ordina-jworks/microservices-dashboard#59]

**Comment by ryandegruyter** [comment]
Do you mean types like microservices/db/resource/ etc. 

or these?
function getGroups() {
      return $q(function(resolve) {
        resolve([
          { key: 'BCI', value: 'BCI' },
          { key: 'BPS', value: 'BPS' },
          { key: 'BUSC', value: 'BUSC' },
          { key: 'CRMODS', value: 'CRMODS' },
          { key: 'CSL', value: 'CSL' },
          { key: 'IMA', value: 'IMA' },
          { key: 'MBP', value: 'MBP' },
          { key: 'NGRP', value: 'NGRP' },
          { key: 'OCT', value: 'OCT' },
          { key: 'PDB', value: 'PDB' },
          { key: 'PPT', value: 'PPT' },
          { key: 'RHE', value: 'RHE' },
          { key: 'ROSY', value: 'ROSY' },
          { key: 'SAPACHE', value: 'SAPACHE' }
        ]);
      });
    }

**Comment by andreasevers** [comment]
The latter!

**Comment by ryandegruyter** [comment]
#62

**Comment by andreasevers** [comment]
Awesome, thanks!
