### ISSUE TITLE
Hovering behaviour seems off in "add node" popup window

### ISSUE THREAD

**Issue by bart-blommaerts** [ordina-jworks/microservices-dashboard#78]
In the "add node" popup window, when you hover over a title (eg. Name) a hand icon is displayed, but no actions are linked to the title .. Hovering should only display the hand icon, when you can fire an action (eg. a hyperlink)

**Comment by ryandegruyter** [comment]
nice catch I'll make a PR tommorow

**Comment by TYsewyn** [comment]
Closing since this was merged.
