### ISSUE TITLE
Empty dropdown is selectable in "add node" popup window

### ISSUE THREAD

**Issue by bart-blommaerts** [ordina-jworks/microservices-dashboard#79]
When adding a node when no groups are existing yet, the group dropdown box is selectable, but it doesn't contain any content.

![image](https://cloud.githubusercontent.com/assets/3988458/17347847/40b9df00-58c7-11e6-9904-a7c3d1548fd3.png)

As requested from https://github.com/ordina-jworks/microservices-dashboard-server/issues/36#issuecomment-237068475

**Comment by bart-blommaerts** [comment]
Other small issue related to the selection of dropdowns:

Selecting a type is only available in "edit" mode not in "create" mode.

**Comment by andreasevers** [comment]
That's because you're clicking a "create node" button in one of the columns, indicating you want the type of that column.

For the backend column though, it's still a valid issue since we want to be able to select one of many options there (SOAP, DB, REST, JMS).

**Comment by bart-blommaerts** [comment]
Can the type be pre-filled in the dropdown then? (if it's known)

**Comment by ryandegruyter** [comment]
It prefills when the group is known, for example if you click on the user microservice it will select the FUNCTIONAL group.

**Comment by TYsewyn** [comment]
Since we're going to rebuild the UI from scratch I'm closing this issue.
If you still have any questions, don't hesitate to reach out on [Gitter](https://gitter.im/ordina-jworks/microservices-dashboard) or open a new issue!
