### ISSUE TITLE
Creating new labels for virtual nodes is no longer possible

### ISSUE THREAD

**Issue by andreasevers** [ordina-jworks/microservices-dashboard#80]
There used to be the possibility to add fields (key value pairs).

<img width="942" alt="screen shot 2016-08-02 at 22 47 14" src="https://cloud.githubusercontent.com/assets/6663110/17355111/19e3e9ca-5903-11e6-9b5e-812bd22c445e.png">

**Comment by ryandegruyter** [comment]
my bad, I refactored the modal. Angular 2 branch will have e2e tests so we can prevent these situations! :)

**Comment by TYsewyn** [comment]
Since we're going to rebuild the UI from scratch I'm closing this issue.
If you still have any questions, don't hesitate to reach out on [Gitter](https://gitter.im/ordina-jworks/microservices-dashboard) or open a new issue!
