### ISSUE TITLE
Create a filter component

### ISSUE THREAD

**Issue by ryandegruyter** [ordina-jworks/microservices-dashboard#85]
![image](https://cloud.githubusercontent.com/assets/12190633/17367041/8916c32c-598e-11e6-9f91-8484f26240d3.png)
- add a folder **filter** in the **app/** folder
- create a file **filter-component.ts** and define your component 
- create a file **filter.html** and define the html template for the component

The HTML template should contain
- 1 button
- 1 input box
- 3 select boxes

**Comment by TYsewyn** [comment]
Since we're going to rebuild the UI from scratch I'm closing this issue.
If you still have any questions, don't hesitate to reach out on [Gitter](https://gitter.im/ordina-jworks/microservices-dashboard) or open a new issue!
