### ISSUE TITLE
Empty Dashboard

### ISSUE THREAD

**Issue by openjack** [ordina-jworks/microservices-dashboard#86]
Using Spring 1.4.0
Added log4j2 and excluded logback classic and core
Using Eureka discovery client
Using Spring Boot config client

The /graph endpoint is showing all of the data that we expect to see in the dashboard out-of-the-box but my dashboard is empty.

There are no errors in the browser console, there are no errors in the server logs.

The app looks like this:

`
@EnableDiscoveryClient
@EnableMicroservicesDashboardServer
@SpringBootApplication
public class Application {
	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
}
`

(spring.application.name = dashboard-web)

I've attached:
output from dashboard-web/graph
output from config-service/dashboard-web/test-dcos
screenshot showing the application running with those configs

[config.txt](https://github.com/ordina-jworks/microservices-dashboard/files/400247/config.txt)
[graph.txt](https://github.com/ordina-jworks/microservices-dashboard/files/400227/graph.txt)
![screen shot 2016-08-03 at 2 33 57 pm](https://cloud.githubusercontent.com/assets/10221826/17379306/63fc57c0-5987-11e6-9bce-5d132e3a34b4.png)

**Comment by openjack** [comment]
I should add that I'm using version 1.0.0 :

<dependency>
			<groupId>be.ordina</groupId>
			<artifactId>microservices-dashboard-server</artifactId>
			<version>1.0.0</version>
</dependency>

**Comment by andreasevers** [comment]
Hey @openjack, if you check the Network tab of either Firebug or Chrome developer tools, do you see a call going out from the dashboard UI?
I suspect the UI making a call to the wrong URL.

**Comment by openjack** [comment]
Yep, that was it.  Looks like it's trying to use port 8080 even though server.port is something else.

**Comment by openjack** [comment]
How to I make it so that the web doesn't call to http://localhost:8080 but instead uses the current host and port?

**Comment by ryandegruyter** [comment]
Hey Jack, you can configure the BASE_URL in the angular module.config:
https://github.com/ordina-jworks/microservices-dashboard/blob/master/src/app/index.config.js
