### ISSUE TITLE
add the Montserrat font

### ISSUE THREAD

**Issue by ryandegruyter** [ordina-jworks/microservices-dashboard#87]

**Comment by scheuchzer** [comment]
+1

We don't have an internet connection in our prod environment. The loading of the ui takes 20+ seconds because the page tries to load that font from google.

**Comment by TYsewyn** [comment]
Since we're going to rebuild the UI from scratch I'm closing this issue.
If you still have any questions, don't hesitate to reach out on [Gitter](https://gitter.im/ordina-jworks/microservices-dashboard) or open a new issue!
