### ISSUE TITLE
Create legend component

### ISSUE THREAD

**Issue by ryandegruyter** [ordina-jworks/microservices-dashboard#89]
![image](https://cloud.githubusercontent.com/assets/12190633/17429122/500809c8-5aed-11e6-85e3-a8da115152d0.png)

**Comment by TYsewyn** [comment]
Since we're going to rebuild the UI from scratch I'm closing this issue.
If you still have any questions, don't hesitate to reach out on [Gitter](https://gitter.im/ordina-jworks/microservices-dashboard) or open a new issue!
