### ISSUE TITLE
Setup tasks in pom.xml

### ISSUE THREAD

**Issue by ryandegruyter** [ordina-jworks/microservices-dashboard#96]

**Comment by andreasevers** [comment]
Any specifics I can help with?

**Comment by ryandegruyter** [comment]
Can you proof read and check if anything is missing? 

We still need to configure CI like running tests, but I'm not sure where to configure this. Is this in the pom.xml or somewhere on codeship? I can provide the build pipeline commands:

- npm install
- npm test
- **npm run e2e**
- npm run build:prod

To run e2e tests we need to configure codeship,

I can also generate code coverage, just need to know to which format and where to send.

**Comment by TYsewyn** [comment]
Since we're going to rebuild the UI from scratch I'm closing this issue.
If you still have any questions, don't hesitate to reach out on [Gitter](https://gitter.im/ordina-jworks/microservices-dashboard) or open a new issue!
