### ISSUE TITLE
Need more details

### ISSUE THREAD

**Issue by pradeepsingh1234** [ordina-jworks/microservices-dashboard#98]
I am reading docs and have below scenario and trying to undersand how can I map my existing services to dashboard.

1- I have 10 microservices(example :- service1 , service 2 .......service10), which are calling each other and using rabbit, radis and mongo db.
2- I want to see the above mocroservices in dahsboard, how to map above services in dashboard ?

**Comment by TYsewyn** [comment]
Thanks for trying out the dashboard!

This repository contains only the frontend part though.
Are you running the dashboard server?
You can find a sample application that uses wiremock in the samples directory of [the server repository](https://github.com/ordina-jworks/microservices-dashboard-server).

You can also ask us questions directly using [Gitter](https://gitter.im/ordina-jworks/microservices-dashboard)

**Comment by pradeepsingh1234** [comment]
In server , do I need to refer eureka to get my service display on dashboard ?

Sent from my iPhone

On Aug 28, 2016, at 11:58 AM, Tim Ysewyn <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for trying out the dashboard!

This repository contains only the frontend part though.
Are you running the dashboard server?
You can find a sample application that uses wiremock in the samples directory of the server repository<https://github.com/ordina-jworks/microservices-dashboard-server>.

You can also ask us questions directly using Gitter<https://gitter.im/ordina-jworks/microservices-dashboard>

-

**Comment by TYsewyn** [comment]
Yes, by pointing the dashboard server to your eureka registry it will find all 10 microservices.
You can use this [application.yml](https://github.com/ordina-jworks/microservices-dashboard-server/blob/master/samples/microservices-dashboard-simple-mocks/src/main/resources/application.yml) as a reference, just make sure to change the default zone url.

**Comment by pradeepsingh1234** [comment]
Thank you.

Sent from my iPhone

On Aug 28, 2016, at 12:41 PM, Tim Ysewyn <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, by pointing the dashboard server to your eureka registry it will find all 10 microservices.
You can use this application.yml<https://github.com/ordina-jworks/microservices-dashboard-server/blob/master/samples/microservices-dashboard-simple-mocks/src/main/resources/application.yml> as a reference, just make sure to change the default zone url.

-

**Comment by TYsewyn** [comment]
You're welcome. I'll close this issue for now.
If you ever need help, you can always create an issue here or talk to us on [Gitter](https://gitter.im/ordina-jworks/microservices-dashboard)!

**Comment by pradeepsingh1234** [comment]
One qq , I have a peering eureka cluster. How can I specify eureka url in dashboard server property file ?

Sent from my iPhone

On Aug 28, 2016, at 12:41 PM, Tim Ysewyn <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, by pointing the dashboard server to your eureka registry it will find all 10 microservices.
You can use this application.yml<https://github.com/ordina-jworks/microservices-dashboard-server/blob/master/samples/microservices-dashboard-simple-mocks/src/main/resources/application.yml> as a reference, just make sure to change the default zone url.

-

**Comment by TYsewyn** [comment]
You just need to specify the url of one of the peers and it should be all set.
If you would like to configure multiple availability zones, you can add multiple key-values to the `eureka.client.serviceUrl` property.

See [EurekaClientConfigBean](http://github.com/spring-cloud/spring-cloud-netflix/tree/master/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaClientConfigBean.java) for more details of the configurable options.
